"""align schema with design diagram

Revision ID: 0c4c0ae7a0bc
Revises: 759632447d13
Create Date: 2026-05-12 23:39:22.677029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c4c0ae7a0bc'
down_revision = '759632447d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dept_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_reports_dept_id_departments'), 'departments', ['dept_id'], ['dept_id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))

    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('dept_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_teachers_dept_id_departments'), 'departments', ['dept_id'], ['dept_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_teachers_dept_id_departments'), type_='foreignkey')
        batch_op.drop_column('dept_id')
        batch_op.drop_column('last_login')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_reports_dept_id_departments'), type_='foreignkey')
        batch_op.drop_column('dept_id')

    # ### end Alembic commands ###
