"""initial migration

Revision ID: 759632447d13
Revises: 
Create Date: 2026-05-12 23:30:12.072871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759632447d13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('dept_name', sa.String(), nullable=False),
    sa.Column('dept_code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('dept_id', name=op.f('pk_departments')),
    sa.UniqueConstraint('dept_code', name=op.f('uq_departments_dept_code'))
    )
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('join_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('teacher_id', name=op.f('pk_teachers')),
    sa.UniqueConstraint('email', name=op.f('uq_teachers_email'))
    )
    op.create_table('reports',
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('average_attendance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('fk_reports_teacher_id_teachers')),
    sa.PrimaryKeyConstraint('report_id', name=op.f('pk_reports'))
    )
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_code', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], name=op.f('fk_students_dept_id_departments')),
    sa.PrimaryKeyConstraint('student_id', name=op.f('pk_students')),
    sa.UniqueConstraint('email', name=op.f('uq_students_email')),
    sa.UniqueConstraint('student_code', name=op.f('uq_students_student_code'))
    )
    op.create_table('devices',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('registration_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('fk_devices_student_id_students')),
    sa.PrimaryKeyConstraint('device_id', name=op.f('pk_devices')),
    sa.UniqueConstraint('mac_address', name=op.f('uq_devices_mac_address'))
    )
    op.create_table('attendance_logs',
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name=op.f('fk_attendance_logs_device_id_devices')),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('fk_attendance_logs_student_id_students')),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_attendance_logs'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_logs')
    op.drop_table('devices')
    op.drop_table('students')
    op.drop_table('reports')
    op.drop_table('teachers')
    op.drop_table('departments')
    # ### end Alembic commands ###
